### ISSUE TITLE
Unable to start - 'No such file or directory'

### ISSUE THREAD

**Issue by NaruZosa** [Pe46dro/XBackBone-docker#23]
Terminal output:
```
D:\Docker\docker-compose\xbackbone>docker-compose up
Creating network "xbackbone_default" with the default driver
Creating xbackbone_xbackbone_1 ... done
Attaching to xbackbone_xbackbone_1
xbackbone_1  | -> Executing /opt/docker/provision/entrypoint.d/01-app.sh
xbackbone_1  | mv: can't rename '/app/config.example.php': No such file or directory
```
Upon manually downloading the config.example.php file and moving it to D:\Docker\xbackbone (where /app is mounted) the error changes to the following:
```

D:\Docker\docker-compose\xbackbone>docker-compose up
Creating network "xbackbone_default" with the default driver
Creating xbackbone_xbackbone_1 ... done
Attaching to xbackbone_xbackbone_1
xbackbone_1  | -> Executing /opt/docker/provision/entrypoint.d/01-app.sh
xbackbone_1  | Could not open input file: /app/bin/migrate
xbackbone_1  | Could not open input file: /app/bin/migrate
xbackbone_xbackbone_1 exited with code 1
xbackbone_1  | Could not open input file: /app/bin/migrate
xbackbone_xbackbone_1 exited with code 1
```

docker-compose.yml contents:

```
version: '3.8'

services:
  xbackbone:
    image: pe46dro/xbackbone-docker
    volumes:
      - D:\Docker\xbackbone:/app/
    ports:
      - 8752:80
    restart: unless-stopped
```

**Comment by Pe46dro** [comment]
The defined volumes are:
https://github.com/Pe46dro/XBackBone-docker/blob/89c0e6008a4c0d3c39be5f808df4230bb1302012/src/Dockerfile#L19

You can also check the docker-compose from the repo:
https://github.com/Pe46dro/XBackBone-docker/blob/89c0e6008a4c0d3c39be5f808df4230bb1302012/docker-compose.yml#L17-L21

**Comment by NaruZosa** [comment]
Thank you :)

I thought it would be possible to mount all locations at once, but as you can see, seems that isn't the case.


In regards to the dockerfile, would it be possible to tidy it up a bit? Maybe something like the following:

```
version: '3.8'

services:
  xbackbone:
    image: pe46dro/xbackbone-docker
    #uncomment the following two lines if using a database container
    #depends_on:
    # - "db"
    volumes:
      - xbackbone/storage:/app/storage 
      - xbackbone/database:/app/resources/database 
      - xbackbone/logs:/app/logs 
      - xbackbone/config:/app/config 
    env_file:
      - ./xbb.env
    environment:
    #Ensure the URL has no trailing slashes
      - URL=https://your.url.com
    ports:
      - 8888:80
    restart: unless-stopped

#Optional, only required if not using sqlite.
#db:
#    image: mariadb:10.4
#    restart: unless-stopped
#    env_file:
#      - ./xbb.env
#    ports:
#     - 3333:3306
#    volumes:
#      - /mariadb:/var/lib/mysql
```

If it's simpler, it's easier to use and modify. The current dockerfile has a bit of extra bloat.
