### ISSUE TITLE
Weird error on starting the image

### ISSUE THREAD

**Issue by oleggtro** [Pe46dro/XBackBone-docker#31]
I tried to start the image and it boots up without errors, but if I try to access the website it constantly fails with "404 Not Found".
I start with a docker compose file due to my traefik config.
Logs don't seem to include anything suspicious:
```xbb    | -> Executing /opt/docker/provision/entrypoint.d/01-app.sh
xbb    | If you are upgrading from a previous version, please run a "php bin/clean".
xbb    | Done.
xbb    | -> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
xbb    | -> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
xbb    | -> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
xbb    | -> Executing /opt/docker/provision/entrypoint.d/20-php.sh
xbb    | -> Executing /opt/docker/bin/service.d/supervisor.d//10-init.sh
xbb    | 2021-03-17 23:27:28,000 INFO Included extra file "/opt/docker/etc/supervisor.d/cron.conf" during parsing
xbb    | 2021-03-17 23:27:28,000 INFO Included extra file "/opt/docker/etc/supervisor.d/dnsmasq.conf" during parsing
xbb    | 2021-03-17 23:27:28,000 INFO Included extra file "/opt/docker/etc/supervisor.d/nginx.conf" during parsing
xbb    | 2021-03-17 23:27:28,001 INFO Included extra file "/opt/docker/etc/supervisor.d/php-fpm.conf" during parsing
xbb    | 2021-03-17 23:27:28,001 INFO Included extra file "/opt/docker/etc/supervisor.d/postfix.conf" during parsing
xbb    | 2021-03-17 23:27:28,001 INFO Included extra file "/opt/docker/etc/supervisor.d/ssh.conf" during parsing
xbb    | 2021-03-17 23:27:28,001 INFO Included extra file "/opt/docker/etc/supervisor.d/syslog.conf" during parsing
xbb    | 2021-03-17 23:27:28,001 INFO Set uid to user 0 succeeded
xbb    | 2021-03-17 23:27:28,016 INFO RPC interface 'supervisor' initialized
xbb    | 2021-03-17 23:27:28,016 INFO supervisord started with pid 1
xbb    | 2021-03-17 23:27:29,020 INFO spawned: 'syslogd' with pid 55
xbb    | 2021-03-17 23:27:29,024 INFO spawned: 'nginxd' with pid 56
xbb    | 2021-03-17 23:27:29,028 INFO spawned: 'php-fpmd' with pid 57
xbb    | 2021-03-17 23:27:29,032 INFO spawned: 'crond' with pid 58
xbb    | -> Executing /opt/docker/bin/service.d/syslog-ng.d//10-init.sh
xbb    | 2021-03-17 23:27:29,044 INFO success: nginxd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
xbb    | 2021-03-17 23:27:29,044 INFO success: php-fpmd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
xbb    | 2021-03-17 23:27:29,045 INFO success: crond entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
xbb    | -> Executing /opt/docker/bin/service.d/nginx.d//10-init.sh
xbb    | -> Executing /opt/docker/bin/service.d/php-fpm.d//10-init.sh
xbb    | Setting php-fpm user to application
xbb    | [2021-03-17T23:27:29.064969] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
xbb    | [SYSLOG] syslog-ng[55]: syslog-ng starting up; version='3.19.1'
xbb    | -> Executing /opt/docker/bin/service.d/cron.d//10-init.sh
xbb    | [17-Mar-2021 23:27:29] NOTICE: fpm is running, pid 57
xbb    | [17-Mar-2021 23:27:29] NOTICE: ready to handle connections
xbb    | 2021-03-17 23:27:30,206 INFO success: syslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:33 +0000 "GET /index.php" 404 /app/index.php 313.696 10240 98.82%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:33 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:34 +0000 "GET /index.php" 404 /app/index.php 23.696 2048 84.40%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:34 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:35 +0000 "GET /index.php" 404 /app/index.php 16.725 2048 119.58%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:35 +0000] "GET /home HTTP/1.1" 404 4296 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:35 +0000 "GET /index.php" 404 /app/index.php 13.017 2048 76.82%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:35 +0000] "GET /home HTTP/1.1" 404 4296 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:35 +0000 "GET /index.php" 404 /app/index.php 12.481 2048 80.12%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:35 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:36 +0000 "GET /index.php" 404 /app/index.php 17.611 2048 56.78%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:36 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:36 +0000 "GET /index.php" 404 /app/index.php 11.476 2048 87.14%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:36 +0000] "GET /home HTTP/1.1" 404 4296 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:37 +0000 "GET /index.php" 404 /app/index.php 13.896 2048 71.96%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:37 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
xbb    | [php-fpm:access] 127.0.0.1 -  17/Mar/2021:23:27:48 +0000 "GET /index.php" 404 /app/index.php 18.276 2048 109.43%
xbb    | 172.26.0.6 - - [17/Mar/2021:23:27:48 +0000] "GET /home HTTP/1.1" 404 4290 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
```

And this is my compose file: 
```yml
version: '3'
services:
  xbb:
    image:  pe46dro/xbackbone-docker
    container_name: xbb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xbackbone.entrypoints=http"
      - "traefik.http.routers.xbackbone.rule=Host(`i.example.com`)"
      - "traefik.http.routers.xbackbone-secure.entrypoints=https"
      - "traefik.http.routers.xbackbone-secure.rule=Host(`i.example.com`)"
      - "traefik.http.routers.xbackbone-secure.tls=true"
      - "traefik.http.routers.xbackbone-secure.tls.certresolver=cloudflare"

    environment:
      - APP_NAME=XBackBone
      - URL=http:\/\/i.example.com\/

networks:
  proxy:
    external: true
```
